export const sections = [
  {
    id: 0,
    heading: 'Speisen und Getränke',
    imgURL: `${import.meta.env.BASE_URL}assets/images/bg__cola.jpg`,
    imgALT: 'Bild von Coca-Cola',
  },
  {
    id: 1,
    heading: 'Unsere Bestseller!',
    imgURL: `${import.meta.env.BASE_URL}assets/images/bg__burger.png`,
    imgALT: 'Bild von Burger',
  },
  ,
  {
    id: 2,
    heading: 'Tageskarte',
    imgURL: `${import.meta.env.BASE_URL}assets/images/bg__pommes.jpg`,
    imgALT: 'Bild von Pommes',
  },
]

export const menu = [
  {
    id: 0,
    name: 'Currywurst mit oder ohne Darm',
    price: '2,50€',
    vegan: false,
    extras: '',
  },
  {
    id: 1,
    name: 'Currywurst mit Brötchen',
    price: '2.70€',
    vegan: false,
    extras: '',
  },
  {
    id: 2,
    name: '2 Currywurst mit Pommes',
    price: '7.50€',
    vegan: false,
    extras: 'rot-weiß',
  },
  {
    id: 3,
    name: '1 Currywurst mit Pommes und Bouletle',
    price: '7.50€',
    vegan: false,
    extras: '',
  },
  {
    id: 4,
    name: 'Currywurst Vegan',
    price: '3.00€',
    vegan: true,
    extras: '',
  },
  {
    id: 5,
    name: 'Bratwust im Brötchen',
    price: '3.00€',
    vegan: false,
    extras: '',
  },
  {
    id: 6,
    name: 'Boulette',
    price: '2.50€',
    vegan: false,
    extras: '',
  },
  {
    id: 7,
    name: 'Paniertes Schweineschnitzel mit Beilage',
    price: '8.00€',
    vegan: false,
    extras: '(frisch geklopt)',
  },
  {
    id: 8,
    name: 'Großes Paniertes Schweineschnitzel mit Beilage',
    price: '9.50€',
    vegan: false,
    extras: '(frisch geklopft)',
  },
  {
    id: 9,
    name: 'Schnitzel a la Cordon Bleu mit Beilage ',
    price: '11.00€',
    vegan: false,
    extras: '(Schweineschnitzel gefüllt mit Käse und Schinken)',
  },
  {
    id: 10,
    name: 'Hamburger',
    price: '5.00€',
    vegan: false,
    extras: 'mit Soße und Salat',
  },
  {
    id: 11,
    name: 'Double Hamburger',
    price: '3.00€',
    vegan: false,
    extras: 'mit Soße und Salat',
  },
  {
    id: 12,
    name: 'Bacon',
    price: '1.20€',
    vegan: false,
    extras: '',
  },
  {
    id: 13,
    name: 'Cheddar-Käse',
    price: '1.00€',
    vegan: false,
    extras: '',
  },
  {
    id: 14,
    name: 'Gefüllte Pljeskavica + Beilage',
    price: '12.00€',
    vegan: false,
    extras: '(Hacksteak gefüllt mit Schäfskäse)',
  },
  {
    id: 15,
    name: 'Pljeskavica + Beilage',
    price: '9.00€',
    vegan: false,
    extras: '(Hacksteak)',
  },
  {
    id: 16,
    name: 'Fleischspieß',
    price: '4.00€',
    vegan: false,
    extras: '',
  },
  {
    id: 17,
    name: 'Cevapcici 5 Stück',
    price: '9.00€',
    vegan: false,
    extras: 'mit Pommes oder Djuvecreis',
  },
  {
    id: 18,
    name: 'Cevapcici 8 Stück',
    price: '12.50€',
    vegan: false,
    extras: 'mit Pommes oder Djuvecreis',
  },
  {
    id: 19,
    name: 'Krautsalat Essig Öl',
    price: '2.80€',
    vegan: false,
    extras: '',
  },
  {
    id: 20,
    name: 'Kartoffelsalat Essig Öl',
    price: '2,80€',
    vegan: false,
    extras: '',
  },
  {
    id: 21,
    name: 'Nudelsalat Mayo',
    price: '2,80€',
    vegan: false,
    extras: '',
  },
  {
    id: 23,
    name: 'Pommes',
    price: '2.80€',
    vegan: false,
    extras: '',
  },
  {
    id: 24,
    name: 'Pommes Groß',
    price: '3.50€',
    vegan: false,
    extras: '',
  },
  {
    id: 25,
    name: 'Frische Bratkartoffeln',
    price: '3.50€',
    vegan: false,
    extras: '',
  },
  {
    id: 26,
    name: 'Djuvecreis',
    price: '2.80€',
    vegan: false,
    extras: '',
  },
  {
    id: 27,
    name: 'Ajvar',
    price: '0.80€',
    vegan: false,
    extras: '',
  },
  {
    id: 28,
    name: 'Vegane Mayo',
    price: '0.50€',
    vegan: true,
    extras: '',
  },
  {
    id: 29,
    name: 'Ketchup / Mayo',
    price: '0.30€',
    vegan: false,
    extras: '',
  },
  {
    id: 30,
    name: 'Zwiebeln Roh oder scharf',
    price: '0.30€',
    vegan: false,
    extras: '',
  },
  {
    id: 31,
    name: 'Gedünstete Zwiebel',
    price: '0.50€',
    vegan: false,
    extras: '',
  },
  {
    id: 32,
    name: 'Brötchen',
    price: '0.30€',
    vegan: false,
    extras: '',
  },
]

export const bestseller = [
  {
    id: 0,
    heading: 'Der beste Hamburger im ganzen Wedding  (versprochen!)',
    description: 'mit Bacon, Cheddar-Käse, Soße und Salat',
    imgURL: `${import.meta.env.BASE_URL}assets/images/bestseller__1.png`,
    imgALT: 'Bild von Hamburger',
    price: '10.20€',
  },
  {
    id: 1,
    heading: 'Cevapcici nach -geheimer- hauseigener Rezept',
    description: '5 Stück mit Pommes und Djuvecreis',
    imgURL: `${import.meta.env.BASE_URL}assets/images/bestseller__2.png`,
    imgALT: 'Bild von Currywurst',
    price: '7.50€',
  },
]

export const tageskarte = [
  {
    id: 0,
    heading: 'ffgfgdgfdgff',
    description: 'dfsfdsfsfdfsdfffdsfds',
    price: '12.40',
  },
]
